# This file was generated by GoReleaser. DO NOT EDIT.
cask "driveignore" do
  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "440f5d0637180bd3342a93454a93f273a254003899a88acd28668efbfc474889"
      url "https://github.com/ranokay/driveignore/releases/download/v#{version}/driveignore_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ee473138b967f4d534041f941e8a8b4a5ae89e53b42099401b698818c06c6ce4"
      url "https://github.com/ranokay/driveignore/releases/download/v#{version}/driveignore_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d91cbaf5015d74a77684b75ba14641150e43ac929ecbcab4d3fca83c084b31f8"
      url "https://github.com/ranokay/driveignore/releases/download/v#{version}/driveignore_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4c63088fa756479c4c947959a715266ebe315de7522f81bcaad25fbb569d54b1"
      url "https://github.com/ranokay/driveignore/releases/download/v#{version}/driveignore_#{version}_linux_amd64.tar.gz"
    end
  end

  name "driveignore"
  desc "Hardlink files into Google Drive while honoring .driveignore"
  homepage "https://github.com/ranokay/driveignore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "driveignore"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/driveignore"]
    end
  end

  # No zap stanza required
end
