# This file was generated by GoReleaser. DO NOT EDIT.
cask "driveignore" do
  version "1.3.1"

  on_macos do
    on_arm do
      sha256 "a926ec3b7c2493049a4733ca14f373c88a487443178a9c0c4a3523b8fa01f013"
      url "https://github.com/ranokay/driveignore/releases/download/v#{version}/driveignore_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d60ae3ef0fb5bd917169f8e54e90427aeaefaaae1a34a4bcd90573d4c2b25c0f"
      url "https://github.com/ranokay/driveignore/releases/download/v#{version}/driveignore_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c3363265e9ef05cadb3775fd084b3b4c32eddba80a9831bebabe5d83abf31838"
      url "https://github.com/ranokay/driveignore/releases/download/v#{version}/driveignore_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d3d60983685039bdf8483ac61ca8cd558f32976d885e88ac9418afa566114e7b"
      url "https://github.com/ranokay/driveignore/releases/download/v#{version}/driveignore_#{version}_linux_amd64.tar.gz"
    end
  end

  name "driveignore"
  desc "Hardlink files into Google Drive while honoring .driveignore"
  homepage "https://github.com/ranokay/driveignore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "driveignore"

  postflight_steps do
    if OS.mac?
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "driveignore"], chdir: "."
    end
  end

  # No zap stanza required
end
