# This file was generated by GoReleaser. DO NOT EDIT.
cask "driveignore" do
  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "ec93a59f1b1b8ce02b68725daa0fb16f9387e3ef390bfce3abba25cf90211687"
      url "https://github.com/ranokay/driveignore/releases/download/v#{version}/driveignore_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc3ceede73bd21fc6ce833e406b7a8473a563b86d76f7ce82a939826d3bd3b99"
      url "https://github.com/ranokay/driveignore/releases/download/v#{version}/driveignore_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "42a9f7119d6a6299d3d8d760303e1580798a8eb0a75777db43b9b0657fce3ee3"
      url "https://github.com/ranokay/driveignore/releases/download/v#{version}/driveignore_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0c3672365ae9f76805d95e67068316867ce56102974bd0655936c26ac76e63ee"
      url "https://github.com/ranokay/driveignore/releases/download/v#{version}/driveignore_#{version}_linux_amd64.tar.gz"
    end
  end

  name "driveignore"
  desc "Hardlink files into Google Drive while honoring .driveignore"
  homepage "https://github.com/ranokay/driveignore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "driveignore"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/driveignore"]
    end
  end

  # No zap stanza required
end
